### ISSUE TITLE
Pacman failed to install missing dependencies

### ISSUE THREAD

**Issue by VictorRodas99** [Its-Satyajit/phpenv#2]
Hi, i found your tool in an arch forum, sorry if I misspell something, english is not my first language.
In a fresh installation of your tool, the first thing that I wanted to do was run the following command:

 `  `  ` bash
 phpv -i 81
  `  `  ` 
  
  but it throws an error, I don't know if I did something wrong, i try to check the c-client and I ran the PKGBUILD script, but it didn't change anything, I though it was something related to that
  
here's the full error output after trying to install a php version
 
  FYI: Stirring up some magic to update PHP version 81...
From https://aur.archlinux.org/php81
 * branch            master     -> FETCH_HEAD
Already up to date.
FYI: Mixing potions to build and install PHP version 81...
FYI: This may take a while... Gather 'round, wizards!
==> Making package: php81 8.1.29-3 (Fri 20 Sep 2024 08:38:23 PM -04)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
[sudo] password for victor:
:: There are 6 providers available for smtp-forwarder:
:: Repository extra
   1) dma  2) exim  3) msmtp-mta  4) nullmailer  5) opensmtpd  6) postfix

Enter a number (default=1):
error: target not found: c-client
:: There are 6 providers available for smtp-forwarder:
:: Repository extra
   1) dma  2) exim  3) msmtp-mta  4) nullmailer  5) opensmtpd  6) postfix

Enter a number (default=1):
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> patchelf
  -> smtp-forwarder
  -> postgresql-libs
  -> unixodbc
  -> libfbclient
  -> freetds
  -> tidy
  -> aspell
  -> libvoikko
  -> hspell
  -> nuspell
  -> aspell
  -> c-client
  -> smtp-forwarder
==> ERROR: Could not resolve all dependencies.
Oops... Failed the incantation to build or install PHP version 81. Did someone mispronounce 'makepkg'?

**Comment by scristian9** [comment]
I had this issue :zipper_mouth_face:

**Comment by JSlomian** [comment]
Same problem with 8.1 and 8.2

```❯ phpv -i 82
FYI: Conjuring PHP version 82 from https://aur.archlinux.org/php82.git... *poof!*
Cloning into '/home/jslomian/src/php82'...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 139 (delta 86), reused 105 (delta 56), pack-reused 0 (from 0)
Receiving objects: 100% (139/139), 66.02 KiB | 598.00 KiB/s, done.
Resolving deltas: 100% (86/86), done.
FYI: Mixing potions to build and install PHP version 82...
FYI: This may take a while... Gather 'round, wizards!
==> Making package: php82 8.2.24-1 (Sun 17 Nov 2024 09:40:25 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
[sudo] password for jslomian: 
:: There are 6 providers available for smtp-forwarder:
:: Repository extra
   1) dma  2) exim  3) msmtp-mta  4) nullmailer  5) opensmtpd  6) postfix

Enter a number (default=1): 
error: target not found: c-client
:: There are 6 providers available for smtp-forwarder:
:: Repository extra
   1) dma  2) exim  3) msmtp-mta  4) nullmailer  5) opensmtpd  6) postfix

Enter a number (default=1): 
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> patchelf
  -> smtp-forwarder
  -> apache
  -> postgresql-libs
  -> libfbclient
  -> freetds
  -> gd
  -> tidy
  -> aspell
  -> libvoikko
  -> hspell
  -> hunspell
  -> nuspell
  -> aspell
  -> net-snmp
  -> c-client
  -> smtp-forwarder
==> ERROR: Could not resolve all dependencies.
Oops... Failed the incantation to build or install PHP version 82. Did someone mispronounce 'makepkg'?

**Comment by Its-Satyajit** [comment]
@VictorRodas99 @JSlomian

refer https://github.com/Its-Satyajit/phpv/issues/1
